---
stages:
  - preflight
  - build

variables:
  DOCKER_DRIVER: overlay
  IMAGE_TAG: registry.gitlab.com/robconnolly/docker-ttrss:latest

services:
  - docker:dind

# Generic preflight template
.preflight: &preflight
  stage: preflight
  tags:
    - docker

# Preflight jobs
yamllint:
  <<: *preflight
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
  script:
    - yamllint .

hadolint:
  <<: *preflight
  image: hadolint/hadolint
  before_script:
    - hadolint -- version
  script:
    - hadolint Dockerfile

build:
  stage: build
  image: docker:latest
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  tags:
    - docker
