image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  IMAGE_TAG: registry.gitlab.com/robconnolly/docker-ttrss:latest

services:
  - docker:dind

before_script:
  - docker info
    
build:
    stage: build
    script:
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
      - docker build -t $IMAGE_TAG .
      - docker push $IMAGE_TAG
          
